### ISSUE TITLE
Incorrect behaviour when change the scale

### ISSUE THREAD

**Issue by Akurosia** [Arrenton/KingdomHeartsPlugin#1]
I play on a 2k monitor and when i change the scale from 1.0 to e.g. 0.,725, the long bar does not scale in relation to the rest of the ui
![Advanced_Combat_Tracker_9xCqAul9Ft](https://user-images.githubusercontent.com/7465469/124380275-29e88a00-dcbc-11eb-94d5-d5ae6a6264d2.png)

**Comment by Arrenton** [comment]
This was fixed with the release of 1.0.0.2 in testing.
