### ISSUE TITLE
Disappears when playing with Controller

### ISSUE THREAD

**Issue by Astral-Crescent** [Arrenton/KingdomHeartsPlugin#13]
UI for this plugin completely disappears when in gamepad mode, which breaks my heart because I find the KH UI extremely accessible to my vision needs and I was excited to use it only to find it will not work with  controller-- which I need because of my disabilities. Please consider making it compatible with gamepad/controller UI mode? Please?

**Comment by Arrenton** [comment]
Found the issue. For now you can fix it by just unchecking "Hide when dialogue box is shown".
This setting actually reads if hotbar 1 is disabled, not hidden. I will add a fix for it.
