### ISSUE TITLE
Portrait bug

### ISSUE THREAD

**Issue by KuniHDT** [Arrenton/KingdomHeartsPlugin#15]
I'm liking how the new portrait feature works so far. Thank you for your hard work!

However, I'm not sure if it's only me but I encountered a bug where the portrait turns black when getting attacked during the danger state. It happens every time. I suspect the hurt and the danger portraits were somehow overlapping each other.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/46819355/140303841-a62890f6-9184-447c-8aa2-0ed05a6091b0.gif)

Besides, is it possible to toggle/customize the reddish on the portrait upon getting damaged?

**Comment by Arrenton** [comment]
This was fixed in 1.0.2.0. =)
