### ISSUE TITLE
Feature Request: Turn off red portrait flashing

### ISSUE THREAD

**Issue by himea-saito** [Arrenton/KingdomHeartsPlugin#18]
Hello, this is possibly the greatest UI mod I've ever used. Absolutely love it!

As the title says, I would like to be able to disable the portrait flashing red when damage is taken. I am using a custom portrait and the red doesn't fit very well.

**Comment by Arrenton** [comment]
That'll be easy enough to do. Expect it in an update after this issue is closed.
