### ISSUE TITLE
[Suggestion] Add option for HP bar to be % based?

### ISSUE THREAD

**Issue by Robro-33** [Arrenton/KingdomHeartsPlugin#19]
As of right now users can set up the bar so that the the bar finishes curving around the portrait at x health and it gains length for every y health until z hp where it stops growing. Is it possible to add an option where users set the maximum length of the bar in pixels and then have the entire bar fill evenly based on your hp% instead?
The current way makes it so that if you have classes at various levels, swap between tank and other roles often, or do synced content frequently, the bar's length and how much hp each part of the bar represents on different parts of the bar constantly shifts. Fixing it as a user needs a manual adjustment to all the health settings every time you go into a duty to get the bar to be consistent between duties and roles meanwhile if there was an hp% based setting instead of just hp value based this would be alleviated.

**Comment by Arrenton** [comment]
If you mean no change in actual length, you could set the full ring to 1 HP and max length to 2, then adjust the width of the long bar accordingly. This would make it behave like you're asking.

**Comment by Robro-33** [comment]
Didnt see when the reply came in, my bad. But yeah, thats exactly that I was looking for! Thank You!
