### ISSUE TITLE
Huge transparent space around ui prevents clicking things

### ISSUE THREAD

**Issue by Astral-Crescent** [Arrenton/KingdomHeartsPlugin#20]
This has been going on for me for a while and was waiting to see if it would be fixed this patch. You did fix my controller issue (yay) but now I still can't like. Click anything around the uh. UI...  
here is a gif demonstrating the issue
![ezgif-7-9c791371a0d6](https://user-images.githubusercontent.com/92853912/141079437-c37a7e4f-f304-4c7b-bb6c-f914aa1ae05c.gif)

**Comment by Arrenton** [comment]
See Issue #6
