### ISSUE TITLE
[Suggestion] Add option to make UI sit behind other HUD elements.

### ISSUE THREAD

**Issue by BleuMage** [Arrenton/KingdomHeartsPlugin#26]
I have this problem where the Kingdom Hearts UI covers item tooltips and my inventory and I can't read the text. I don't know if it's possible to make it sit behind everything, but I would greatly appreciate it.

**Comment by Arrenton** [comment]
This isn't possible. The way Dalamud/ImGUI works for FFXIV is that it draws on a layer on top of the game.

**Comment by BleuMage** [comment]
Ah, got it. I thought it might be something like that. No problem, I'll just fit the UI around it. This thing is too cool not to use.
