### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by Delaene** [Arrenton/KingdomHeartsPlugin#27]
![image](https://user-images.githubusercontent.com/42815462/146647901-44da4e29-311d-40e7-b061-68e583e61e4f.png)
Seems that scaling the general UI doesn't resize level and current class, could it be possible to make it so everything gets resized? This screenshot was taken at 80% scaling.
I've seen there's a specific section where you can choose the level/job position but there's no way to resize job
![image](https://user-images.githubusercontent.com/42815462/146647950-256f8d19-8b77-4178-b6db-dda33831a957.png)

**Comment by Arrenton** [comment]
Seems like I just missed these in the global scale.
I'll get it fixed
