### ISSUE TITLE
[Suggestion] Add / command for hiding without disable

### ISSUE THREAD

**Issue by TheMetaWolfe** [Arrenton/KingdomHeartsPlugin#3]
There's no way to hide the bars once they're up unless you disable the plugin, which makes making HUD layouts difficult. It would be nice if a / command could be implemented for easy hiding while also being applicable to macros when wanting to easily transition to other HUD layouts.

**Comment by Arrenton** [comment]
To be honest, I never actually noticed it when I was talking to NPCs, but I can see how that can be an issue. I'll add an additional command to hide the UI and look in to hiding when dialogue boxes are up.

**Comment by RosskoCholakov** [comment]
If it's of any help, you can also enable these options in Dalamund's options, Look & Feel
![Screenshot (2)](https://user-images.githubusercontent.com/67242516/136666423-369c0084-0cb8-47b2-8070-6c468e88ffa9.png)
