### ISSUE TITLE
Needs an update for 6.1 Compatability

### ISSUE THREAD

**Issue by DiZ21** [Arrenton/KingdomHeartsPlugin#34]
This is probably one of my favourite plugins.
I beg, please update this.

**Comment by Arrenton** [comment]
Ah, it's finally time. I'll get to it as quickly as I can.

**Comment by MrSunabouzu** [comment]
Thank you!!! I'm a gamepad player who started in feb and I prefer this mod over the normal ui.

**Comment by BleuMage** [comment]
I actually don't know what I would do without this plugin. I love it to fucking pieces. I even made separate little transparent portraits for my character. I can't wait for it to be updated. <3 <3 <3

**Comment by RiledUp42** [comment]
Big same as said above. I love this plugin, especially the low HP warning and how you can configure it. The whole thing is damn brilliant and it looks SO cool.

**Comment by Arrenton** [comment]
I just posted the update to the plugin repository, so once it's merged you should be able to get it on the plugin installer.
