### ISSUE TITLE
can't get the portraits to work

### ISSUE THREAD

**Issue by DangerousDoughnut** [Arrenton/KingdomHeartsPlugin#36]
i've been trying to get the portraits to work but for some reason all i'm getting is a black circle. the pathway seems to be correct, as far as i can tell? i'd love to get the portraits working, so any advice on what i'm doing wrong would be much appreciated ^^;
![Image 1](https://user-images.githubusercontent.com/105244171/167499302-0e282b2d-544d-4c6b-af96-f80afd4b60b7.jpg)
![Image 2](https://user-images.githubusercontent.com/105244171/167499323-f7a2d6ca-2bb5-4ad8-89fd-0cb9e49e58d1.jpg)
![Image 3](https://user-images.githubusercontent.com/105244171/167499331-91f1d5bb-19d3-4dfb-b4ba-5bcfee8891d5.jpg)

**Comment by DangerousDoughnut** [comment]
turns out i forgot a space, disregard ><

**Comment by Arrenton** [comment]
Looks like the image name has a space. 'Image 19.png'

**Comment by DangerousDoughnut** [comment]
yeah, i just realised
