### ISSUE TITLE
[Issue] Job icon cannot be moved or edited.

### ISSUE THREAD

**Issue by BleuMage** [Arrenton/KingdomHeartsPlugin#38]
As the title says. It also ignored my old setting and just set it smack dab in the center of the portrait element. I just turned it off for now, but you might have an idea on how to fix it.

**Comment by Arrenton** [comment]
Ah... another issue since the API update for dalamud. I got an idea how to fix it.

**Comment by BleuMage** [comment]
Strangely, that seems to be the only thing. And I don't believe I missed anything.
