### ISSUE TITLE
[Suggestion] Better resource text customization

### ISSUE THREAD

**Issue by TheMetaWolfe** [Arrenton/KingdomHeartsPlugin#4]
While I understand that in KH all values are displayed strictly through the bars, because of FFXIV's emphasis on numerical values (especially with MP, GP, and CP), it'd be nice to have more control over the resource values' text, such as making them bigger or moving them around like you would any other part of the HUD.

**Comment by Arrenton** [comment]
The text for MP/GP/Etc, can be moved already. Though, I could make everything else movable such as the class icon, level, and HP value.

**Comment by TheMetaWolfe** [comment]
They can be moved, yes, but unless you expand the entire scale of the UI, the numbers are really small, for example. I personally believe the class icon and level were good where they were, but the HP and MP/GP/CP numbers could be given an option for size alteration along with their existing positioning option. I guess you could also add an option for the XP numbers, but I don't think it's too big of a deal compared to the other numbers.

**Comment by Arrenton** [comment]
Ah, gotcha. Yeah, I did notice that the text becomes almost unreadable when scaled below 75%.
I can add an option for that.
