### ISSUE TITLE
Pls update asap :( this is one of my favorite plugins

### ISSUE THREAD

**Issue by Kazuhiro74** [Arrenton/KingdomHeartsPlugin#40]
Hey y'all,
I'm sure you're working hard. I love this plugin so much. Just wanted to let you know I look forward to being able to use it again!

**Comment by Arrenton** [comment]
There's a new process to their methods of updating plugins that I do not understand yet. It may take some time for me to get it figured out as I'm pretty slow at learning these things.

**Comment by Astral-Crescent** [comment]
You have my strongest encouragements and support. I find this game utterly unplayable without this extension due to my mental disabilities making it hard to track tiny ui elements and KH is weirdly enough the only HUD I've ever liked so to say this is a favorite plugin would be an understatement. I am cheering you on.

**Comment by Superskull85** [comment]
Hi. I was wondering if you had any updates regarding pushing a new version? Also, could you use any help getting through the new process?

**Comment by Keylink1** [comment]
I would also like to know if there is an ETA, and hoping you get all the help you need to update this!

**Comment by Arrenton** [comment]
There is no ETA, but I did get it posted to the testing channel some time ago for checking if it's working correctly.

**Comment by fartsandstinks** [comment]
Can't tell you how much your follow up even though you might not play anymore is appreciated! This is my favorite plugin and having to bounce all over my screen for HP/MP/LB/LVL/EXP has been hell lol. Thanks again!

**Comment by LudwigKH** [comment]
Made an account to say thank you so much for updating the pluggin, I know you dont play the game, but this is a huge qol improvement for me :)

**Comment by fartsandstinks** [comment]
And you fixed the job icon! Thank you so much!!!

**Comment by Arrenton** [comment]
I'm happy to hear the update went through!

I tested everything i could using the trial account and it seemed to work as intended.

Be sure to let me know here if there are further issues!
