### ISSUE TITLE
Dawntrail Support

### ISSUE THREAD

**Issue by DTV96Calibre** [Arrenton/KingdomHeartsPlugin#47]
It's been a little while since this plugin has seen activity. Will you be updating it for the latest Dalamud API 10?

**Comment by shikiwolf** [comment]
sorry to ask
how to update plugin?
my version still are 1.0.7.0

**Comment by DTV96Calibre** [comment]
@shikiwolf Plugin updates are done through Dalamud in-game. The Dalamud team is having some trouble with their github service account, so the update will be delayed until they sort that out.

**Comment by FoxyWolfMeerkat** [comment]
Plugin still nonfunctional.  Due to github Dalamud problem still?

**Comment by shikiwolf** [comment]
I think problem still not fix maybe just wait....

**Comment by shikiwolf** [comment]
Is anyone suceess update?XD"

**Comment by Arrenton** [comment]
The update should be available. I updated it weeks ago.
