### ISSUE TITLE
[Suggestion] Health bar shaking toggle

### ISSUE THREAD

**Issue by RosskoCholakov** [Arrenton/KingdomHeartsPlugin#5]
I would like to be able to outright disable (maybe the easier option) or significantly reduce the HP bar shaking when i'm struck. I really is distracting and annoying. A toggle option and/or shake regulation bar would suffice

**Comment by Arrenton** [comment]
I can add a slider to control how aggressive it is with the option of 0.
I didn't think of this being an issue so nothing of the sort was implemented.

**Comment by RosskoCholakov** [comment]
Not a big deal but would be a progress for the addon for sure
