### ISSUE TITLE
[Issue] Transparent non-click trough zone below UI element

### ISSUE THREAD

**Issue by RosskoCholakov** [Arrenton/KingdomHeartsPlugin#6]
I have a transparent layer below the HP bar that blocks me from clicking anything behind it. I can still mouse over buttons and see their names, but when i try to click them, I instead click on the invisible layer and nothing happens. If i have the UI element unlocked, for example, instead of clicking on the button, i can freely move the addon. Will attach a screenshot with supposed layer dimensions
![Screenshot (1)](https://user-images.githubusercontent.com/67242516/136654852-a5e19379-4b14-4311-8e66-2ec4524d7fec.png)
.

**Comment by Arrenton** [comment]
Thanks for making posting this. I wasn't aware of it because I always had it exactly in the lower left corner of my screen haha. I'll check it out.

**Comment by RosskoCholakov** [comment]
Thanks for the quick response. Yes, i did lower the scale abit. Yes, i tried what you said and it works.
