### ISSUE TITLE
[Suggestion] A default bar size for PvP modes

### ISSUE THREAD

**Issue by solitonmedic** [Arrenton/KingdomHeartsPlugin#9]
![image](https://user-images.githubusercontent.com/14916963/137614399-7879393f-f712-4b0e-b2fd-5b17c37a70bb.png)

Whenever we're doing Frontline or Feast modes, where our HP is at a certain specific value, can we have our HP bars forced to this size during these instances?

**Comment by Arrenton** [comment]
I have never done PvP, so I had no idea this was a thing.
So are you asking for a separate size config for PvP? I'm not 100% sure the API can tell me if in PvP or not. But if available I can do that easily.

**Comment by solitonmedic** [comment]
> 
> 
> I have never done PvP, so I had no idea this was a thing. So are you asking for a separate size config for PvP? I'm not 100% sure the API can tell me if in PvP or not. But if available I can do that easily.

Yes, that's right. At least force the bar to look like the picture above when entering the Wolves' Den and the Frontline/Rival Wings/the Feast modes.
